# Generated by Django 2.0.1 on 2018-05-18 03:16

from django.db import migrations, models
import django.db.models.deletion
import try_and_guess.models.game


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.IntegerField(default=0)),
                ('range_min', models.IntegerField(default=1)),
                ('range_max', models.IntegerField(default=100)),
                ('guesser', models.CharField(choices=[(try_and_guess.models.game.GuesserChoice(('USER',)), ('USER',)), (try_and_guess.models.game.GuesserChoice('MACHINE'), 'MACHINE')], default=try_and_guess.models.game.GuesserChoice(('USER',)), max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='try_and_guess.GameStatus'),
        ),
    ]
