# Generated by Django 2.0.1 on 2018-05-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'START'), (1, 'USER_GUESSING'), (2, 'MACHINE_GUESSING'), (3, 'FINISHED')], default='START', max_length=25)),
                ('guess_number', models.IntegerField(default=0)),
                ('range_min', models.IntegerField(default=1)),
                ('range_max', models.IntegerField(default=100)),
                ('guesser', models.CharField(choices=[(0, 'USER'), (1, 'MACHINE')], default='USER', max_length=15)),
            ],
        ),
    ]
