# Generated by Django 2.0.1 on 2018-05-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try_and_guess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guesser',
            field=models.CharField(default='USER', max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='START', max_length=25),
        ),
    ]
