# Generated by Django 2.0.1 on 2018-05-18 20:21

from django.db import migrations, models
import try_and_guess.models.game


class Migration(migrations.Migration):

    dependencies = [
        ('try_and_guess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[(try_and_guess.models.game.GameStatusChoice(('START',)), ('START',)), (try_and_guess.models.game.GameStatusChoice(('USER_GUESSING',)), ('USER_GUESSING',)), (try_and_guess.models.game.GameStatusChoice(('MACHINE_GUESSING',)), ('MACHINE_GUESSING',)), (try_and_guess.models.game.GameStatusChoice('FINISHED'), 'FINISHED')], default=try_and_guess.models.game.GameStatusChoice(('START',)), max_length=25),
        ),
    ]
